### ISSUE TITLE
[실전 카프카 개발부터 운영까지] 12장. 엔터프라이즈 카프카 아키텍처 구성 사례

### ISSUE THREAD

**Issue by kmg28801** [kmg28801/kafka-study#22]

**Comment by taewoo-kim123** [comment]
# 12장 엔터프라이즈 카프카 아키텍처 구성 사례
* 지금까지 배운 내용을 모두 종합해 실제로 쓰이는 엔터프라이즈용 카프카 아키텍처를 설계해보고, 환경을 구성하는 목차
* 콘솔 실습은 생략하고, 대신 스키마 레지스트리와 프로듀서, 컨슈머를 이용해 메세지 주고받고, 카프카 커넥트를 이용해 2개의 카프카 클러스터를 미러링 하는 동작을 구성

## 12.1 엔터프라이즈용 카프카 아키텍처의 개요
* 엔터프라이즈 환경에서는 장애 복구 등을 위해 하나 이상의 데이터 센터를 운영, 관리하는 경우가 많음.
* 카프카 클러스터 역시 다수의 데이터 센터에 배치되어 있으므로, 데이터 리플리케이션은 필수.
* 카프카 간의 데이터 리플리에키션에는 미러 메이커를 사용한다.
![스크린샷 2023-09-01 오후 10 05 23](https://github.com/kmg28801/kafka-study/assets/122066644/2ff04323-9957-4808-967d-cb59b441fe7b)


* 왼쪽은 업스트림과 다운 스트림 사이에서 리플리케이션이 필요,
* 오른쪽은 여러 데이터센터마다 카프카가 존재하고, 중앙에 있는 카프카 클러스터로 합쳐진 데이터를 모으기 위해 리플리케이션을 사용하기도 함
* 중앙에 모인 데이터는 실시간 처리와 분석을 위해 다른 어플리케이션에 적재가 된다. (예시로 하둡, 엘라스틱서치, S3, HBase가 있음)
![image](https://github.com/kmg28801/kafka-study/assets/122066644/3b427481-9229-42ec-be36-fd491366cc00)
* 위 그림이 지금까지 진행한 내용을 종합한 엔터프라이즈 환경
* 카프카 클러스터는 총 2개로, 업스트림 클러스터, 다운스트림 카프카가 존재하고, 다운스트림 카프카는 업스트림 카프카를 미러링.
* 이걸 구현해보자....
## 12.2 엔터프라이즈용 카프카의 환경 구성
![스크린샷 2023-09-01 오후 10 06 18](https://github.com/kmg28801/kafka-study/assets/122066644/32de4d52-7bc9-4694-adba-267223e84588)
* 실습을 위해 준비된 서버는 총 6대
* 기존 peter-kafka01~03 에는 업스트림 카프카, zk01~03 에는 다운스트림 카프카를 구성
* 주키퍼는 2개의 앙상블을 구성하지 않고 1개의 앙상블만 구성하고, 지노드를 분리해 카프카 클러스터 2개가 하나의 주키퍼 앙상블을 바라보도록 구성
* 카프카 커넥트가 업스트림이 아닌 다운 스트림과 함께있음.
* 미러링에서 가장 중요한건 메시지 손실이 없어야 한다는 점
  * 카프카의 미러링 순서
  1. 업스트림 카프카의 토픽에서 메시지를 읽어온다.
  2. 업스트림 카프카에서 읽은 메시지를 다운 스트림 카프카의 토픽으로 전송
  => 즉 미러링 동작은 프로듀서 + 컨슈머 동작으로 이뤄져있다.
* 카프카 커넥트가 x 서버에 위치할때 해당 서버와는 로컬 네트워크를 통해 통신을 하므로 데이터 유실이 없음.
* 만약 업스트림 쪽에 있다면, 프로듀싱하는데에 로컬 통신이라 데이터 유실이 없지만 다운스트림으로 데이터를 보낼때 유실이 발생하면 복구 방법이 없음
* 하지만 다운스트림쪽에 있고, 데이터를 프로듀싱 할때 네트워크 에러가 난다면, 컨슈머의 오프셋을 장애 전 시점으로만 변경 한다면 일부 메시지의 중복 발행은 일어나지만, 메시지 유실은 없다.

`peter-ansible01` 서버에 접속하고, 아래 명령어를 실행하여 그람과 같은 환경으로 설치를 한다.
1. `ansible-playbook -i hosts site.yml` 명령어 실행
```
[ec2-user@ip-172-31-13-207 ~]$ cd kafka2
[ec2-user@ip-172-31-13-207 kafka2]$ cd chapter12/ansible_playbook/
[ec2-user@ip-172-31-13-207 ansible_playbook]$ ansible-playbook -i hosts site.yml
```
  * 은근 오래걸림, 중간에 `TASK [stop exporters]` 이거 failed 나는데 `ignoring` 처리됨(상관 없나?) 나머진 순조롭게 ok
![스크린샷 2023-09-01 오후 10 07 57](https://github.com/kmg28801/kafka-study/assets/122066644/c79fae07-315f-4f5f-8203-d15621ffcc8e)
![스크린샷 2023-09-01 오후 10 08 19](https://github.com/kmg28801/kafka-study/assets/122066644/b21faa2f-b2a4-4d34-aae3-1cf707850adc)

2. `ansible-playbook -i hosts expoter.yml`
  * `TASK [exporterall : stop services] ` failed 나는데 ignoring 처리됨
![스크린샷 2023-09-01 오후 10 08 42](https://github.com/kmg28801/kafka-study/assets/122066644/a76dc176-8fa3-484d-9319-e49d0c7f06bd)
3. `ansible-playbook -i hosts monitoring.yml `
![스크린샷 2023-09-01 오후 10 08 52](https://github.com/kmg28801/kafka-study/assets/122066644/a021c4de-9903-41cc-95f9-15b38bd1de8d)
## 12.3 엔터프라이즈용 카프카의 운영 실습
* 전체 실습 시나리오는 다음과 같다
1. 프로듀서1은 업스트림 카프카의 실습용 토픽(peter-avro01-kafka1)으로 메세지를 전송
2. 카프카 커넥트의 미러 메이커는 `peter-avro01-kafka1` 토픽을 다운스트림 카프카로 미러링 
3. 컨슈머1을 이용해 업스트림 카프카의 `peter-avro01-kafka1` 토픽을 컨슘
4. 컨슈머2를 이용해 다운스트림 카프카의 미러링된 토픽 `src.peter-avro01-kafka1`에서 메세지를 읽고, 엘라스틱서지로 전송
5. REST API와 키바나를 이용해 엘라스틱 서치에 메세지가 저장되었는지 확인
6. 스키마를 변경한 후, 다시 메세지를 전송해 최종적으로 엘라스틱까지 변경되 스키마 내용이 적용되었는지 확인
7. 이 과정에 대한 카프카 메트릭은 프로메테우스에 저장되며, 그라파나 대시보드를 이용해 모니터링

### 12.3.1 CMAK를 이용한 토픽 생성
* peter-kafka01의 퍼블릭 주소의 9000번 포트로 접근 
* 왼쪽 상단의 `Cluster` 를 누르고, `Add Cluster`를 선택하면 클러스터의 상세 정보를 입력하게끔 화면이 바뀜
![스크린샷 2023-09-01 오후 10 10 09](https://github.com/kmg28801/kafka-study/assets/122066644/06b6fdf0-e6ee-4f71-9b57-b72f1c9698f3)
* 클러스터 이름은 `kafka-1` 주키퍼 호스트에는 `peter-zk01.foo.bar:2181,peter-zk02.foo.bar:2181,peter-zk03.foo.bar:2181/kafka3` 를 입력
* `Enable JMX Polling` 활성화 하고, 저장
* `kafka-2` 도 등록을 해주기, 호스트 주소는`peter-zk01.foo.bar:2181,peter-zk02.foo.bar:2181,peter-zk03.foo.bar:2181/kafka4` 를 입력
* 클러스터 등록 완료
* 토픽 이름은 `peter-avro01-kafka1`, 파티션은 1, Replication Factor는 3으로 설정하고 생성
### 12.3.2 카프카 커넥트 설정
* 카프카 커넥터가 잘 실행되고 있는지 확인
* 앤서블 서버에서 `curl http://peter-zk01.foo.bar:8083/connectors` 를 요청해서 카프카 커넥트가 실행되고 있는지 확인
```
[ec2-user@ip-172-31-13-207 ansible_playbook]$ curl http://peter-zk01.foo.bar:8083/connectors
[][ec2-user@ip-172-31-13-207 ansible_playbook]$ 
```
* 8083에서 실행되고있으며, 등록된 커넥터가 없어서 `[]`로 출력
* 아래를 복사해서 커넥터 등록
```
curl --header "Content-Type: application/json" --header "Accept: application/json" --request PUT --data '{"name": "peter-mirrormaker2","connector.class": "org.apache.kafka.connect.mirror.MirrorSourceConnector","tasks.max": "1","source.cluster.alias": "src","target.cluster.alias": "dst","source.cluster.bootstrap.servers": "peter-kafka01.foo.bar:9092,peter-kafka02.foo.bar:9092,peter-kafka03.foo.bar:9092","target.cluster.bootstrap.servers": "peter-zk01.foo.bar:9092,peter-zk02.foo.bar:9092,peter-zk03.foo.bar:9092","replication.factor": "3","topics": "peter-avro01-kafka1" }' http://peter-zk01.foo.bar:8083/connectors/peter-mirrormaker2/config
```
* `curl http://peter-zk01.foo.bar:8083/connectors/peter-mirrormaker2/status | python -m json.tool` 를 이용해서 카프카 커넥트가 잘 등록되었는지 확인
```
[ec2-user@ip-172-31-13-207 ansible_playbook]$ curl http://peter-zk01.foo.bar:8083/connectors/peter-mirrormaker2/status | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   176  100   176    0     0  15488      0 --:--:-- --:--:-- --:--:-- 16000
{
    "connector": {
        "state": "RUNNING",
        "worker_id": "172.31.0.34:8083"
    },
    "name": "peter-mirrormaker2",
    "tasks": [
        {
            "id": 0,
            "state": "RUNNING",
            "worker_id": "172.31.0.34:8083"
        }
    ],
    "type": "source"
}
[ec2-user@ip-172-31-13-207 ansible_playbook]$ 
```
![스크린샷 2023-09-01 오후 10 10 38](https://github.com/kmg28801/kafka-study/assets/122066644/7b2a37e5-ec6e-47a0-81b6-e251c64c3c66)
* CMAK에서 Cluster -> List -> kafka-2 -> Topic -> List 를 통해 kafka-2의 토픽들을 볼수 있는데 위 사진처럼 `src.peter-avro01-kafka1`로 미러링 된것을 확인 할 수 있다.

### 12.3.3 모니터링 환경 구성
* `peter-kafka01` 서버에 그라파나, 프로메테우스가 설치되어 있으며, 3000번 포트를 이용해 접근할 수 있다.
* 7장에서 실습한 p237`그라파나 대시보드 생성` 을 참고해서 프로메테우스 연동
* 단 이름은 `Prometheus`, URL을 `http://peter-kafka01.foo.bar:9090` 으로 입력
* 그리고 Kafka Metrics 대시보드 (`https://github.com/onlybooks/kafka2/blob/main/chapter7/kafka_metrics.json` 복붙)
![스크린샷 2023-09-01 오후 10 11 03](https://github.com/kmg28801/kafka-study/assets/122066644/cdfc70d2-7e6f-4a2d-ae11-571d4f905d1e)
![스크린샷 2023-09-01 오후 10 11 13](https://github.com/kmg28801/kafka-study/assets/122066644/985c4faa-a678-4bce-ba74-d78c608bcbcc)
* Node Exporter 대시보드(`1860` load 얘는 에러남...)
![스크린샷 2023-09-01 오후 10 11 26](https://github.com/kmg28801/kafka-study/assets/122066644/41ee2135-b2a0-4a44-956a-8a43b7e7511b)

### 12.3.4 메세지 전송과 확인
* 파이썬 클라이언트를 직접 구성하고 해당 클라이언트들과 스키마 레지스트리를 이용해 메세지 보내고 받기 실습
* kafka2 git clone, python3 설치 `git clone https://github.com/onlybooks/kafka2` `sudo yum -y install python3`
  (kafka2는 이미 git clone 받아져있고, python3도 이미 설치되어있기때문에 저는 스킵했습니다.)
* `python3 -m venv venv12` 를 이용해 가상환경 생성하고, 진입
```
[ec2-user@ip-172-31-13-207 ~]$ source venv12/bin/activate
(venv12) [ec2-user@ip-172-31-13-207 ~]$ 
```
* `confluent-kafka[avro]`, `names`, `elasticsearch`라이브러리를 설치한다
```
(venv12) [ec2-user@ip-172-31-13-207 ~]$ pip install confluent-kafka[avro]
Collecting confluent-kafka[avro]
  Downloading confluent_kafka-2.2.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 54.2 MB/s eta 0:00:00
Collecting requests
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 KB 12.8 MB/s eta 0:00:00
Collecting avro<2,>=1.11.1
  Downloading avro-1.11.2.tar.gz (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.8/85.8 KB 19.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting fastavro>=1.0
  Downloading fastavro-1.8.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 69.4 MB/s eta 0:00:00
Collecting typing-extensions
  Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.0.4-py3-none-any.whl (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.9/123.9 KB 22.5 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 KB 14.3 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2023.7.22-py3-none-any.whl (158 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.3/158.3 KB 30.4 MB/s eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.2.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.8/175.8 KB 32.6 MB/s eta 0:00:00
Building wheels for collected packages: avro
  Building wheel for avro (pyproject.toml) ... done
  Created wheel for avro: filename=avro-1.11.2-py2.py3-none-any.whl size=119738 sha256=b6e6ddf4376d5137688b267b2497b8900309e3eb1726258aa31cc90172aeff3d
  Stored in directory: /home/ec2-user/.cache/pip/wheels/8d/55/0a/8c5b53acd72980ae94a5524ef458af3f72dfe0cbf2af400716
Successfully built avro
Installing collected packages: confluent-kafka, urllib3, typing-extensions, idna, fastavro, charset-normalizer, certifi, requests, avro
Successfully installed avro-1.11.2 certifi-2023.7.22 charset-normalizer-3.2.0 confluent-kafka-2.2.0 fastavro-1.8.0 idna-3.4 requests-2.31.0 typing-extensions-4.7.1 urllib3-2.0.4
WARNING: You are using pip version 22.0.4; however, version 23.2.1 is available.
You should consider upgrading via the '/home/ec2-user/venv12/bin/python3 -m pip install --upgrade pip' command.
```
```
(venv12) [ec2-user@ip-172-31-13-207 ~]$ pip install names
Collecting names
  Downloading names-0.3.0.tar.gz (789 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 789.1/789.1 KB 35.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for names, since package 'wheel' is not installed.
Installing collected packages: names
  Running setup.py install for names ... done
Successfully installed names-0.3.0
WARNING: You are using pip version 22.0.4; however, version 23.2.1 is available.
You should consider upgrading via the '/home/ec2-user/venv12/bin/python3 -m pip install --upgrade pip' command.
```
```
(venv12) [ec2-user@ip-172-31-13-207 ~]$ pip install elasticsearch
Collecting elasticsearch
  Downloading elasticsearch-8.9.0-py3-none-any.whl (395 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.5/395.5 KB 18.6 MB/s eta 0:00:00
Collecting elastic-transport<9,>=8
  Downloading elastic_transport-8.4.0-py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 KB 13.2 MB/s eta 0:00:00
Requirement already satisfied: certifi in ./venv12/lib/python3.7/site-packages (from elastic-transport<9,>=8->elasticsearch) (2023.7.22)
Collecting urllib3<2,>=1.26.2
  Downloading urllib3-1.26.16-py2.py3-none-any.whl (143 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.1/143.1 KB 25.4 MB/s eta 0:00:00
Installing collected packages: urllib3, elastic-transport, elasticsearch
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.0.4
    Uninstalling urllib3-2.0.4:
      Successfully uninstalled urllib3-2.0.4
Successfully installed elastic-transport-8.4.0 elasticsearch-8.9.0 urllib3-1.26.16
WARNING: You are using pip version 22.0.4; however, version 23.2.1 is available.
You should consider upgrading via the '/home/ec2-user/venv12/bin/python3 -m pip install --upgrade pip' command.
```
* 깃 파일에 미리 정의되어있는에이브로를 활용해 스키마를 정의한다.
* int형 한반(class)에 string형 학생이름(name)이 
* names와 random 모듈을 이용해서 이름과 반을 랜덤하게 총 100개의 데이터를 `peter-avro01-kafka1` 토픽으로 전송
```
(venv12) [ec2-user@ip-172-31-13-207 ~]$ python kafka2/chapter12/python/producer-1_kafka-1_v1.py 
kafka2/chapter12/python/producer-1_kafka-1_v1.py:32: DeprecationWarning: AvroProducer has been deprecated. Use AvroSerializer instead.
  }, default_value_schema=value_schema)
Message delivered to peter-avro01-kafka1 [0]
Message delivered to peter-avro01-kafka1 [1]
Message delivered to peter-avro01-kafka1 [2]
(중간 생략)
Message delivered to peter-avro01-kafka1 [98]
Message delivered to peter-avro01-kafka1 [99]
``` 
* 컨슈머를 이용해 보낸 메세지를 확인 후, 컨슈머 종료
```
(venv12) [ec2-user@ip-172-31-13-207 ~]$ python kafka2/chapter12/python/consumer-1_kafka-1_v1.py 
kafka2/chapter12/python/consumer-1_kafka-1_v1.py:23: DeprecationWarning: AvroConsumer has been deprecated. Use AvroDeserializer instead.
  'schema.registry.url': 'http://peter-kafka03.foo.bar:8081'},reader_value_schema=value_schema)
{'name': 'Marie', 'class': 3}
{'name': 'Michael', 'class': 4}
{'name': 'Joseph', 'class': 1}
(중간생략)
{'name': 'Jerry', 'class': 3}
{'name': 'Emil', 'class': 4}
```
* 엘라스틱서치의 헬스체크 `curl -X GET 'http://peter-kafka02.foo.bar:9200/_cat/health?v'` (status green)확인
```
(venv12) [ec2-user@ip-172-31-13-207 ~]$ curl -X GET 'http://peter-kafka02.foo.bar:9200/_cat/health?v'
epoch      timestamp cluster        status node.total node.data shards pri relo init unassign pending_tasks max_task_wait_time active_shards_percent
1693572689 12:51:29  docker-cluster green           1         1      6   6    0    0        0             0                  -                100.0%
``` 
* 엘라스틱서치에서 데이터단위를 도큐먼트라 부르고, 도큐먼트를 모아놓은것을 인덱스라함.
```
(venv12) [ec2-user@ip-172-31-13-207 ~]$ curl -X GET 'http://peter-kafka02.foo.bar:9200/_cat/indices?v'
health status index                           uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   .kibana_7.12.1_001              -3SuAX7SS1OpYrhjy--t5Q   1   0         11            0      2.1mb          2.1mb
green  open   .apm-custom-link                qSRXTpnlTPue6BRkrIo0mQ   1   0          0            0       208b           208b
green  open   .apm-agent-configuration        Q7x_FEwiTRGeX7pQvHEo4w   1   0          0            0       208b           208b
green  open   .kibana_task_manager_7.12.1_001 UuUIxREwQQ6mtg_Y010lQg   1   0          9         2357    324.4kb        324.4kb
green  open   .kibana-event-log-7.12.1-000001 jG9s0cGARIWKGMdG9oNFZg   1   0          1            0      5.6kb          5.6kb
```
* 출력 내용을 보면, 아직 미러링된 메세지들의 전송이 이뤄지기 전이라, 키바나 관련 인덱스만 출력되어잇음.
* 미러링된 다운스트림 카프카의 `src.peter-avro01-kafka1` 에서 메세지를 읽고, 엘라스틱 서체로 전송(막힘)
 `AvroConsumer` 가 deprecated되었음...
 ```
 (venv12) [ec2-user@ip-172-31-13-207 ~]$ python kafka2/chapter12/python/consumer_kafka-2_producer_es_v1.py 
kafka2/chapter12/python/consumer_kafka-2_producer_es_v1.py:25: DeprecationWarning: AvroConsumer has been deprecated. Use AvroDeserializer instead.
  'schema.registry.url': 'http://peter-kafka03.foo.bar:8081'},reader_value_schema=value_schema)
Traceback (most recent call last):
  File "kafka2/chapter12/python/consumer_kafka-2_producer_es_v1.py", line 29, in <module>
    es = Elasticsearch('peter-kafka02.foo.bar:9200')
  File "/home/ec2-user/venv12/lib64/python3.7/site-packages/elasticsearch/_sync/client/__init__.py", line 345, in __init__
    ssl_show_warn=ssl_show_warn,
  File "/home/ec2-user/venv12/lib64/python3.7/site-packages/elasticsearch/_sync/client/utils.py", line 105, in client_node_configs
    node_configs = hosts_to_node_configs(hosts)
  File "/home/ec2-user/venv12/lib64/python3.7/site-packages/elasticsearch/_sync/client/utils.py", line 143, in hosts_to_node_configs
    return hosts_to_node_configs([hosts])
  File "/home/ec2-user/venv12/lib64/python3.7/site-packages/elasticsearch/_sync/client/utils.py", line 151, in hosts_to_node_configs
    node_configs.append(url_to_node_config(host))
  File "/home/ec2-user/venv12/lib64/python3.7/site-packages/elastic_transport/client_utils.py", line 217, in url_to_node_config
    "URL must include a 'scheme', 'host', and 'port' component (ie 'https://localhost:9200')"
ValueError: URL must include a 'scheme', 'host', and 'port' component (ie 'https://localhost:9200')
 ```

**Comment by taewoo-kim123** [comment]
gpt에게 물어봐서 실습코드에서 `es = Elasticsearch('http://peter-kafka02.foo.bar:9200')` `http` 붙이라고 알려줌.

그런데 새로운 오류가 발생
```
(venv12) [ec2-user@ip-172-31-13-207 ~]$ python kafka2/chapter12/python/consumer_kafka-2_producer_es_v1.py 
kafka2/chapter12/python/consumer_kafka-2_producer_es_v1.py:25: DeprecationWarning: AvroConsumer has been deprecated. Use AvroDeserializer instead.
  'schema.registry.url': 'http://peter-kafka03.foo.bar:8081'},reader_value_schema=value_schema)
{'name': 'Ernest', 'class': 4}
Traceback (most recent call last):
  File "kafka2/chapter12/python/consumer_kafka-2_producer_es_v1.py", line 53, in <module>
    es.indices.create(index=index)
  File "/home/ec2-user/venv12/lib64/python3.7/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/home/ec2-user/venv12/lib64/python3.7/site-packages/elasticsearch/_sync/client/indices.py", line 518, in create
    "PUT", __path, params=__query, headers=__headers, body=__body
  File "/home/ec2-user/venv12/lib64/python3.7/site-packages/elasticsearch/_sync/client/_base.py", line 390, in perform_request
    method, path, params=params, headers=headers, body=body
  File "/home/ec2-user/venv12/lib64/python3.7/site-packages/elasticsearch/_sync/client/_base.py", line 337, in perform_request
    body=resp_body,
elasticsearch.UnsupportedProductError: The client noticed that the server is not Elasticsearch and we do not support this unknown product
```

엘라스틱 서치 상태를 확인하니 아까는 `green`이었는데 이제 `yellow`가 되었음

```
(venv12) [ec2-user@ip-172-31-13-207 ~]$ curl -X GET 'http://peter-kafka02.foo.bar:9200/_cat/health?v'
epoch      timestamp cluster        status node.total node.data shards pri relo init unassign pending_tasks max_task_wait_time active_shards_percent
1694349165 12:32:45  docker-cluster yellow  
```



`[ec2-user@ip-172-31-13-207 ~]$ curl -X GET 'http://peter-kafka02.foo.bar:9200/_cat/indices?v'`
이걸로 상태를 보니 
`yellow open   students                        ITNfSd20S9Kv_dKBi47MXA   1   1          0            0       208b           208b`
 복사개수가 0개

**Comment by taewoo-kim123** [comment]
1. 2서버로 들어가서 도커의 엘라스틱 컨테이너를 재시작 하여도 `yellow`에서 바뀌지 않음
2.로그를 확인하니 `ERROR` 로 따로 찍히는건 없음
3. gpt가 샤드를 확인하라해서 `curl -X GET 'http://peter-kafka02.foo.bar:9200/_cat/shards?v'`를 통해 샤드를 확인

```
index                               shard prirep state      docs   store ip           node
.tasks                              0     p      STARTED       4  21.3kb 172.31.5.249 ip-172-31-5-249.us-east-2.compute.internal
students                            0     p      STARTED       0    208b 172.31.5.249 ip-172-31-5-249.us-east-2.compute.internal
students                            0     r      UNASSIGNED                           
.apm-agent-configuration            0     p      STARTED       0    208b 172.31.5.249 ip-172-31-5-249.us-east-2.compute.internal
.kibana-event-log-7.12.1-000001     0     p      STARTED       4  21.8kb 172.31.5.249 ip-172-31-5-249.us-east-2.compute.internal
.apm-custom-link                    0     p      STARTED       0    208b 172.31.5.249 ip-172-31-5-249.us-east-2.compute.internal
.kibana_task_manager_7.12.1_001     0     p      STARTED       9 188.8kb 172.31.5.249 ip-172-31-5-249.us-east-2.compute.internal
.kibana_7.12.1_001                  0     p      STARTED      11   2.1mb 172.31.5.249 ip-172-31-5-249.us-east-2.compute.internal
.ds-ilm-history-5-2023.09.01-000001 0     p      STARTED                 172.31.5.249 ip-172-31-5-249.us-east-2.compute.internal
```
`students`가 2개 찍혀있고, `UNASSIGNED`로 되어있음....

**Comment by taewoo-kim123** [comment]
노드도 1개중 1개로 확인
```
[ec2-user@ip-172-31-13-207 ~]$ curl -X GET 'http://peter-kafka02.foo.bar:9200/_cat/nodes?v'
ip           heap.percent ram.percent cpu load_1m load_5m load_15m node.role   master name
172.31.5.249           62          97  10    0.08    0.07     0.08 cdfhilmrstw *      ip-172-31-5-249.us-east-2.compute.internal
```

**Comment by taewoo-kim123** [comment]
(venv12) [ec2-user@ip-172-31-13-207 ~]$ python kafka2/chapter12/python/consumer_kafka-2_producer_es_v1.py 
kafka2/chapter12/python/consumer_kafka-2_producer_es_v1.py:25: DeprecationWarning: AvroConsumer has been deprecated. Use AvroDeserializer instead.
  'schema.registry.url': 'http://peter-kafka03.foo.bar:8081'},reader_value_schema=value_schema)
AvroConsumer error: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: src.peter-avro01-kafka1: Broker: Unknown topic or partition"}
^C^X^CTraceback (most recent call last):
  File "kafka2/chapter12/python/consumer_kafka-2_producer_es_v1.py", line 34, in <module>
    msg = c.poll(10)
  File "/home/ec2-user/venv12/lib64/python3.7/site-packages/confluent_kafka/avro/__init__.py", line 174, in poll
    message = super(AvroConsumer, self).poll(timeout)
KeyboardInterrupt
